services:
  twitter:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitter
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data: